Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -87,24 +87,12 @@ jobs:
          haxelib run lime build android -ONLY_ARMV7 -D officialBuild -D LUA_ALLOWED
          find . -name "*.apk"
 
-      - name: Check AndroidManifest # checking whats wrong with manifest
+      - name: Show generated app manifest (pre-merge)
         if: failure()
         run: |
-         echo "=== manifests ==="
-         find export -type f -name "AndroidManifest.xml"
-
-         echo "=== Likely manifest ==="
-         MANIFEST=$(find export -type f -path "*merged_manifests*" -name "AndroidManifest.xml" | head -n 1)
-
-         if [ -f "$MANIFEST" ]; then
-           echo "Found: $MANIFEST"
-           echo "=============================="
-           cat "$MANIFEST"
-           echo "=============================="
-         else
-           echo "manifest not found"
-         fi
-         
+         echo "=== Generated app manifest ==="
+         cat export/release/android/bin/app/src/main/AndroidManifest.xml || echo "Not found"
+          
       - uses: actions/upload-artifact@v4
         with:
           name: androidBuild
